version: '3.9'
services:
  s3:
      image: minio/minio:latest
      command: ["server", "/data", "--console-address", ":9001"]
      volumes:
        - ./s3:/data
      ports: ["127.0.0.1:9000:9000", "127.0.0.1:9001:9001"]

networks:
  default: ~

volumes:
  target: ~
  registry: ~
  git: ~

